### ISSUE TITLE
numpy scimath ImportError on Mac

### ISSUE THREAD

**Issue by cdeil** [astropy/astropy-benchmarks#2]
@mdboom I wanted to try running `astropy-benchmarks` locally on my Mac and ran into this `ImportError` for `scimath` in `numpy`:
https://gist.github.com/cdeil/8400139

**Comment by astrofrog** [comment]
@cdeil - are you still seeing this issue?

**Comment by cdeil** [comment]
I haven't run `astropy-benchmarks` in a long time.
So I don't know if there is still some issue.

Let's just close this now, and re-open in the future if someone runs into this issue again.
