### ISSUE TITLE
Adding an "import astropy" benchmark

### ISSUE THREAD

**Issue by MSeifert04** [astropy/astropy-benchmarks#20]
The issue has come up two times (https://github.com/astropy/astropy/issues/4598, https://github.com/astropy/astropy/issues/5222) in the last months and it would be very nice to spot regressions and/or improvements.

**Comment by astrofrog** [comment]
See also https://github.com/astropy/astropy-benchmarks/pull/15

**Comment by astrofrog** [comment]
This will require https://github.com/airspeed-velocity/asv/pull/487

**Comment by bsipocz** [comment]
This was finally added to `asv`, so we can start writing these benchmarks:
https://github.com/airspeed-velocity/asv/pull/832
