### ISSUE TITLE
Update JSON to display new benchmarks

### ISSUE THREAD

**Issue by pllim** [astropy/astropy-benchmarks#50]
#49 is not appearing in render results page. 

@astrofrog , "I think the issue is that my update script is not updating the `benchmarks.json` file."

**Comment by astrofrog** [comment]
Should be fixed: https://github.com/astropy/astropy-benchmarks/commit/2d4fe909ef5f83b8fd83e3f5bcd0c0f80149ec6b

I've updated my scripts locally to do this automatically

**Comment by astrofrog** [comment]
Confirmed: http://www.astropy.org/astropy-benchmarks/#table.TimeMaskedColumn.time_masked_column_init?y-axis=log :)

**Comment by pllim** [comment]
Thanks!

**Comment by pllim** [comment]
Oh, look at that nice increase of performance!
