### ISSUE TITLE
DOC: Add user guide in readme and contributing.md

### ISSUE THREAD

**Issue by pllim** [astropy/astropy-benchmarks#61]
As discussed on June 22, 2018 telecon. cc @eteq

**Comment by pllim** [comment]
Update: @astrofrog added readme in df673460695b8f6372edeb4af9af9d9e933bf0d5.

Tom, thanks for the readme. Should we include gotchas about running `asv` with multiple cores or VMs? Also, if we can somehow incorporate your Google Drive instructions into a proper doc here, that would be very nice as well.

**Comment by astrofrog** [comment]
I will add the google doc to the astropy developer docs, and once it's there we can link to it from the README here.

**Comment by pllim** [comment]
@astrofrog , wasn't there discussion to also separate out dev doc away from core code doc? Perhaps that is out of scope here...

**Comment by astrofrog** [comment]
In the end I added the instructions to the README here. Closing this!
