### ISSUE TITLE
LICENSE missing

### ISSUE THREAD

**Issue by orbeckst** [astropy/astropy-benchmarks#62]
We would like to use your `cron.sh` script for MDAnalysis/benchmarks#2 but there is no license.

Would you be willing to add an open source license that would make it clear how your code can be used by other projects?

Many thanks!

**Comment by pllim** [comment]
Hi. Thanks for alerting us to this. I have added a license. It is BSD 3-clause like the rest of the Astropy project.

**Comment by orbeckst** [comment]
Thank you very much!
