### ISSUE TITLE
Website not loading

### ISSUE THREAD

**Issue by pv** [astropy/astropy-benchmarks#66]
https://www.astropy.org/astropy-benchmarks/ shows an error message currently (2018-09-09).
Maybe missing `git submodule update --init` if you installed asv from git?

**Comment by astrofrog** [comment]
@pv - has anything changed recently in asv that would cause this? (it was working until recently)

**Comment by astrofrog** [comment]
It looks like the vendor directory is missing from the gh-pages branch

**Comment by pv** [comment]
There's now a git submodule, so you need `git submodule update --init` or let pip do that for you via `pip install git+https://github.com/airspeed-velocity/asv`

**Comment by astrofrog** [comment]
@pv - thanks, I've updated the pip install command in https://github.com/astropy/astropy-benchmarks/commit/31b17d1993481df198427a956cb091d4d27f97b7 - will close this if it ends up working.

**Comment by astrofrog** [comment]
Fixed!
