### ISSUE TITLE
bug in benchmark - but would fix break history?

### ISSUE THREAD

**Issue by hamogu** [astropy/astropy-benchmarks#94]
Looking at the setup for the modelling branchmarks, it look to me that the "medium" array has 2000 entries and the "large" array has only one (or indeed would fail if we used the most current numpy, since the step number is `5e-6`, which is << 1 :
https://github.com/astropy/astropy-benchmarks/blob/master/benchmarks/modeling/model.py#L13
(same for the arrays with units). And indeed the tests with the "large" array run faster than the tests with the medium array...

The fix is easy, just change from `5e-6` to `5e+6` (or better `5000000` because that's an int and not a float) but that would probably make a regression appear? What to do? Fix and rename the test so that it's not compared to the old one?

**Comment by pllim** [comment]
I think we have 2 choices but @astrofrog should decide:

1. Rename and lose history.
2. Keep same name and @astrofrog re-write history. (If I remember correctly, he said it takes a few days.)

**Comment by pllim** [comment]
Also looks like @nden added it in #51, so maybe she could clarify.

**Comment by nden** [comment]
It's obviously a bug. 
These benchmarks were added when rewrite of CompoundModel started. It became clear later that the rewrite was not only performance oriented but also fixed issues related to previous design. In that sense the history before that (4.0) is not interesting, we cannot go back to that version of the code.

I'm fine with either action but 1) is simpler and we don't loose much.

**Comment by astrofrog** [comment]
I think option 1 is the easiest, just rename 'large' to 'big'? Then later we still have the option to go back and compute it for older commits if we want.

**Comment by pllim** [comment]
@hamogu , would you be interested to submit a PR to rename the test + bug fix? 😄
